/**
 * trackTemplates are loaded into the tracks collection using the
 * one-off populatedb function.
 *
 * This information is not used anywhere actively.
 *
 * The trackTemplates array needs to be based on the skills array
 * to make it consistent with other data
 *
 * 0-Yellow
 * 1-Blue
 * 2-Orange
 * 3-Green
 * 4-Red
 * 5-Purple
 * 6-None
 */

const populateTrackData = (skills) => {
  const trackData = [
    {
      display_order: 1,
      name: "C1",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 7 },
        { skill: skills[4], width: 10 },
        { skill: skills[0], width: 5 },
        { skill: skills[2], width: 25 },
        { skill: skills[1], width: 28 },
        { skill: skills[0], width: 17 },
      ],

      obstacle_sequence: "yryoby",
    },
    {
      display_order: 2,
      name: "C2",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 7 },
        { skill: skills[1], width: 22 },
        { skill: skills[4], width: 10 },
        { skill: skills[3], width: 16 },
        { skill: skills[0], width: 10 },
        { skill: skills[3], width: 10 },
        { skill: skills[1], width: 22 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ybrgygby",
    },
    {
      display_order: 3,
      name: "C3",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 12 },
        { skill: skills[4], width: 12 },
        { skill: skills[6], width: 3 },
        { skill: skills[4], width: 10 },
        { skill: skills[1], width: 40 },
        { skill: skills[0], width: 10 },
        { skill: skills[4], width: 10 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yrbyry",
    },
    {
      display_order: 4,
      name: "C4",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[1], width: 15 },
        { skill: skills[0], width: 15 },
        { skill: skills[5], width: 20 },
        { skill: skills[0], width: 10 },
        { skill: skills[4], width: 10 },
        { skill: skills[1], width: 20 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ybypyrby",
    },
    {
      display_order: 5,
      name: "C5",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[4], width: 10 },
        { skill: skills[3], width: 30 },
        { skill: skills[2], width: 8 },
        { skill: skills[0], width: 10 },
        { skill: skills[2], width: 19 },
        { skill: skills[0], width: 12 },
      ],
      obstacle_sequence: "yrgoyoy",
    },
    {
      display_order: 6,
      name: "C6",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 13 },
        { skill: skills[4], width: 30 },
        { skill: skills[2], width: 8 },
        { skill: skills[4], width: 10 },
        { skill: skills[2], width: 8 },
        { skill: skills[4], width: 10 },
        { skill: skills[2], width: 8 },
        { skill: skills[0], width: 5 },
        { skill: skills[2], width: 10 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yrororoyoy",
    },
    {
      display_order: 7,
      name: "C7",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 13 },
        { skill: skills[2], width: 15 },
        { skill: skills[0], width: 5 },
        { skill: skills[2], width: 15 },
        { skill: skills[0], width: 5 },
        { skill: skills[4], width: 6 },
        { skill: skills[2], width: 8 },
        { skill: skills[0], width: 10 },
        { skill: skills[5], width: 20 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yoyoyroypy",
    },

    {
      display_order: 8,
      name: "C8",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[4], width: 13 },
        { skill: skills[3], width: 10 },
        { skill: skills[4], width: 10 },
        { skill: skills[3], width: 10 },
        { skill: skills[4], width: 10 },
        { skill: skills[2], width: 20 },
        { skill: skills[3], width: 18 },
        { skill: skills[0], width: 15 },
      ],
      obstacle_sequence: "yrgrgrogy",
    },
    // 0-Yellow
    // 1-Blue
    // 2-Orange
    // 3-Green
    // 4-Red
    // 5-Purple
    // 6-None
    {
      display_order: 9,
      name: "C9",
      trial_track: true,
      draw_array: [{ skill: skills[0], width: 100 }],
      obstacle_sequence: "zzzzz",
    },
    {
      display_order: 10,
      name: "C10",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 6 },
        { skill: skills[4], width: 10 },
        { skill: skills[0], width: 5 },
        { skill: skills[5], width: 18 },
        { skill: skills[0], width: 5 },
        { skill: skills[4], width: 14 },
        { skill: skills[0], width: 5 },
        { skill: skills[5], width: 18 },
        { skill: skills[0], width: 12 },
      ],

      obstacle_sequence: "yrypyrypy",
    },
    {
      display_order: 11,
      name: "C11",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 13 },
        { skill: skills[2], width: 10 },
        { skill: skills[1], width: 15 },
        { skill: skills[3], width: 10 },
        { skill: skills[0], width: 10 },
        { skill: skills[1], width: 15 },
        { skill: skills[2], width: 10 },
        { skill: skills[3], width: 10 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yobgybogy",
    },

    {
      display_order: 12,
      name: "C12",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 18 },
        { skill: skills[2], width: 10 },
        { skill: skills[4], width: 12 },
        { skill: skills[1], width: 15 },
        { skill: skills[0], width: 5 },
        { skill: skills[4], width: 15 },
        { skill: skills[1], width: 15 },
        { skill: skills[2], width: 15 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yorbyrboy",
    },

    {
      display_order: 13,
      name: "C13",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[3], width: 10 },
        { skill: skills[4], width: 20 },
        { skill: skills[0], width: 15 },
        { skill: skills[3], width: 10 },
        { skill: skills[1], width: 17 },
        { skill: skills[4], width: 15 },
        { skill: skills[1], width: 15 },
        { skill: skills[0], width: 7 },
      ],
      obstacle_sequence: "ygrygbrby",
    },

    {
      display_order: 14,
      name: "C14",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 8 },
        { skill: skills[2], width: 18 },
        { skill: skills[0], width: 5 },
        { skill: skills[4], width: 18 },
        { skill: skills[3], width: 10 },
        { skill: skills[2], width: 10 },
        { skill: skills[4], width: 7 },
        { skill: skills[2], width: 10 },
        { skill: skills[0], width: 10 },
        { skill: skills[3], width: 18 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yoyrgoroygy",
    },
    {
      display_order: 15,
      name: "C15",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[4], width: 16 },
        { skill: skills[1], width: 8 },
        { skill: skills[2], width: 13 },
        { skill: skills[3], width: 8 },
        { skill: skills[4], width: 16 },
        { skill: skills[2], width: 8 },
        { skill: skills[1], width: 20 },
        { skill: skills[3], width: 8 },
        { skill: skills[0], width: 3 },
      ],

      obstacle_sequence: "yrbogrobgy",
    },
    {
      display_order: 16,
      name: "C16",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[5], width: 10 },
        { skill: skills[0], width: 5 },
        { skill: skills[2], width: 13 },
        { skill: skills[1], width: 15 },
        { skill: skills[5], width: 15 },
        { skill: skills[2], width: 10 },
        { skill: skills[1], width: 15 },
        { skill: skills[0], width: 17 },
      ],

      obstacle_sequence: "ypyobpoby",
    },
    {
      display_order: 17,
      name: "C17",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[1], width: 15 },
        { skill: skills[0], width: 10 },
        { skill: skills[3], width: 15 },
        { skill: skills[5], width: 10 },
        { skill: skills[1], width: 10 },
        { skill: skills[3], width: 10 },
        { skill: skills[5], width: 10 },
        { skill: skills[0], width: 12 },
      ],

      obstacle_sequence: "ybygpbgpy",
    },
    {
      display_order: 18,
      name: "C18",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 13 },
        { skill: skills[2], width: 10 },
        { skill: skills[0], width: 10 },
        { skill: skills[3], width: 17 },
        { skill: skills[0], width: 10 },
        { skill: skills[5], width: 10 },
        { skill: skills[2], width: 10 },
        { skill: skills[3], width: 10 },
        { skill: skills[5], width: 16 },
        { skill: skills[0], width: 3 },
      ],

      obstacle_sequence: "yoygypogpy",
    },
    {
      display_order: 19,
      name: "C19",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[3], width: 17 },
        { skill: skills[5], width: 10 },
        { skill: skills[2], width: 15 },
        { skill: skills[1], width: 15 },
        { skill: skills[3], width: 5 },
        { skill: skills[2], width: 10 },
        { skill: skills[1], width: 15 },
        { skill: skills[5], width: 10 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ygpobgobpy",
    },
    {
      display_order: 20,
      name: "C20",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[1], width: 16 },
        { skill: skills[4], width: 11 },
        { skill: skills[0], width: 15 },
        { skill: skills[5], width: 15 },
        { skill: skills[1], width: 11 },
        { skill: skills[0], width: 5 },
        { skill: skills[5], width: 15 },
        { skill: skills[4], width: 20 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ybrypbypry",
    },
    {
      display_order: 21,
      name: "C21",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 13 },
        { skill: skills[4], width: 13 },
        { skill: skills[5], width: 5 },
        { skill: skills[2], width: 8 },
        { skill: skills[0], width: 15 },
        { skill: skills[2], width: 10 },
        { skill: skills[4], width: 15 },
        { skill: skills[5], width: 28 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yrpoyorpy",
    },
    {
      display_order: 22,
      name: "C22",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[1], width: 15 },
        { skill: skills[4], width: 18 },
        { skill: skills[5], width: 5 },
        { skill: skills[2], width: 10 },
        { skill: skills[1], width: 15 },
        { skill: skills[5], width: 20 },
        { skill: skills[4], width: 15 },
        { skill: skills[2], width: 8 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ybrpobproy",
    },
    {
      display_order: 23,
      name: "C23",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[3], width: 16 },
        { skill: skills[0], width: 10 },
        { skill: skills[3], width: 10 },
        { skill: skills[4], width: 16 },
        { skill: skills[5], width: 6 },
        { skill: skills[0], width: 6 },
        { skill: skills[4], width: 7 },
        { skill: skills[0], width: 16 },
        { skill: skills[5], width: 25 },
        { skill: skills[3], width: 5 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ygygrpyrypgy",
    },
    {
      display_order: 24,
      name: "C24",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[1], width: 11 },
        { skill: skills[4], width: 12 },
        { skill: skills[3], width: 11 },
        { skill: skills[5], width: 11 },
        { skill: skills[4], width: 17 },
        { skill: skills[3], width: 11 },
        { skill: skills[1], width: 17 },
        { skill: skills[5], width: 20 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ybrgprgbpy",
    },
    {
      display_order: 25,
      name: "C25",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[2], width: 15 },
        { skill: skills[4], width: 13 },
        { skill: skills[5], width: 11 },
        { skill: skills[3], width: 15 },
        { skill: skills[4], width: 15 },
        { skill: skills[5], width: 15 },
        { skill: skills[2], width: 9 },
        { skill: skills[3], width: 6 },
        { skill: skills[2], width: 9 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yorpgrpogoy",
    },
    {
      display_order: 26,
      name: "D1",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 10 },
        { skill: skills[1], width: 16 },
        { skill: skills[4], width: 6 },
        { skill: skills[1], width: 50 },
        { skill: skills[3], width: 14 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ybrbgy",
    },
    {
      display_order: 27,
      name: "D2",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[5], width: 11 },
        { skill: skills[4], width: 17 },
        { skill: skills[3], width: 11 },
        { skill: skills[5], width: 7 },
        { skill: skills[3], width: 11 },
        { skill: skills[4], width: 25 },
        { skill: skills[3], width: 11 },
        { skill: skills[5], width: 17 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yprgpgrgpy",
    },
    {
      display_order: 28,
      name: "D3",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[5], width: 5 },
        { skill: skills[4], width: 12 },
        { skill: skills[0], width: 10 },
        { skill: skills[2], width: 9 },
        { skill: skills[4], width: 17 },
        { skill: skills[2], width: 9 },
        { skill: skills[4], width: 27 },
        { skill: skills[5], width: 27 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ypryororpy",
    },
    {
      display_order: 29,
      name: "D4",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[3], width: 16 },
        { skill: skills[0], width: 21 },
        { skill: skills[2], width: 10 },
        { skill: skills[0], width: 10 },
        { skill: skills[2], width: 10 },
        { skill: skills[0], width: 10 },
        { skill: skills[2], width: 10 },
        { skill: skills[0], width: 24 },
      ],
      obstacle_sequence: "ygyoyoyoy",
    },
    {
      display_order: 30,
      name: "D5",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[3], width: 10 },
        { skill: skills[4], width: 12 },
        { skill: skills[3], width: 10 },
        { skill: skills[1], width: 20 },
        { skill: skills[2], width: 8 },
        { skill: skills[0], width: 10 },
        { skill: skills[5], width: 19 },
        { skill: skills[3], width: 19 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ygrgboypgy",
    },
    {
      display_order: 31,
      name: "D6",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[1], width: 18 },
        { skill: skills[0], width: 10 },
        { skill: skills[3], width: 13 },
        { skill: skills[4], width: 10 },
        { skill: skills[5], width: 13 },
        { skill: skills[2], width: 13 },
        { skill: skills[1], width: 18 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ybygrpoby",
    },
    {
      display_order: 32,
      name: "D7",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[4], width: 6 },
        { skill: skills[2], width: 9 },
        { skill: skills[4], width: 15 },
        { skill: skills[2], width: 9 },
        { skill: skills[4], width: 6 },
        { skill: skills[5], width: 35 },
        { skill: skills[1], width: 18 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yrororpby",
    },
    {
      display_order: 33,
      name: "D8",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 12 },
        { skill: skills[5], width: 14 },
        { skill: skills[0], width: 10 },
        { skill: skills[3], width: 27 },
        { skill: skills[0], width: 10 },
        { skill: skills[4], width: 19 },
        { skill: skills[0], width: 12 },
      ],
      obstacle_sequence: "ypygyry",
    },
    {
      display_order: 34,
      name: "D9",
      trial_track: true,
      draw_array: [{ skill: skills[0], width: 100 }],
      obstacle_sequence: "zzzzz",
    },
    {
      display_order: 35,
      name: "D10",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[3], width: 15 },
        { skill: skills[4], width: 13 },
        { skill: skills[5], width: 39 },
        { skill: skills[3], width: 12 },
        { skill: skills[2], width: 29 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ygrpgoy",
    },
    {
      display_order: 36,
      name: "CLIMBING",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[4], width: 15 },
        { skill: skills[2], width: 8 },
        { skill: skills[1], width: 15 },
        { skill: skills[4], width: 12 },
        { skill: skills[5], width: 14 },
        { skill: skills[2], width: 15 },
        { skill: skills[4], width: 6 },
        { skill: skills[2], width: 15 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "yrobrporoy",
    },

    {
      display_order: 37,
      name: "DIVING",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[1], width: 25 },
        { skill: skills[4], width: 7 },
        { skill: skills[3], width: 10 },
        { skill: skills[1], width: 23 },
        { skill: skills[4], width: 7 },
        { skill: skills[3], width: 10 },
        { skill: skills[1], width: 23 },
        { skill: skills[0], width: 3 },
      ],
      obstacle_sequence: "ybrgbrgby",
    },
    {
      display_order: 38,
      name: "RUGBY",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 7 },
        { skill: skills[4], width: 21 },
        { skill: skills[0], width: 10 },
        { skill: skills[4], width: 21 },
        { skill: skills[0], width: 10 },
        { skill: skills[4], width: 21 },
        { skill: skills[0], width: 5 },
        { skill: skills[2], width: 5 },
        { skill: skills[0], width: 7 },
      ],
      obstacle_sequence: "yryryryoy",
    },
    {
      display_order: 39,
      name: "TRIATHLON",
      trial_track: true,
      draw_array: [
        { skill: skills[0], width: 3 },
        { skill: skills[1], width: 13 },
        { skill: skills[4], width: 10 },
        { skill: skills[1], width: 13 },
        { skill: skills[4], width: 10 },
        { skill: skills[5], width: 29 },
        { skill: skills[0], width: 24 },
      ],
      obstacle_sequence: "ybrbrpy",
    },
  ];

  return trackData;
};

module.exports = {
  populateTrackData,
};
